apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-akamai-dns
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: alberto.clemente@sisal.it
    privateKeySecretRef:
      name: letsencrypt-akamai-issuer-account-key
    solvers:
    - dns01:
        akamai:
          serviceConsumerDomain: akab-mpkizpacyud5pqeo-isppgo5z6ahduxzc.luna.akamaiapis.net
          clientTokenSecretRef:
            name: akamai-creds
            key: clientToken
          clientSecretSecretRef:
            name: akamai-creds
            key: clientSecret
          accessTokenSecretRef:
            name: akamai-creds
            key: accessToken
